# =============================== Network device ===============================
packetbeat.interfaces.device: any

# =================================== Flows ====================================
# Set `enabled: false` or comment out all options to disable flows reporting.
packetbeat.flows:
  # Set network flow timeout. Flow is killed if no packet is received before being
  # timed out.
  timeout: 30s

  # Configure reporting period. If set to -1, only killed flows will be reported
  period: 10s

# =========================== Transaction protocols ============================

packetbeat.protocols:
- type: mysql
  # Configure the ports where to listen for MySQL traffic. You can disable
  # the MySQL protocol by commenting out the list of ports.
  ports: [3306,3307]

# ================================== Outputs ===================================

output.kafka: 
  hosts: ["{project}.{region}.log.aliyuncs.com:10012"] 
  username: "{project}" 
  password: "{ak}#{sk}" 
  ssl.certificate_authorities: 
  topic: 'general-db-logstore' 
  partition.round_robin: 
    reachable_only: false 

  required_acks: 1 
  compression: gzip 
  max_message_bytes: 1000000

# ================================= Processors =================================
processors:
  - if.contains.tags: forwarded
    then:
      - drop_fields:
          fields: [host]
    else:
      - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

